baseURL = "http://hugo-bucket-rossini.s3-website-us-east-1.amazonaws.com/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"

[[deployment.targets]]
name = "hugo-bucket-rossini"
URL = "s3://hugo-bucket-rossini/region=us-east-1"